print("\n\n~~~~~~~~~~ BAND NAME GENERATOR ~~~~~~~~~~")
print("I'll help you genarate a name for your band if you answer the questions below correctly")
name = input("What is your name: ")
loc = input("Where were you born: ")
addr = input("Where do you live: ")
print("~~~~~~~~~~~~~~~~~ generating name ~~~~~~~~~~~~~~~~~~~~~")
print(loc + " " + name)
print("OR")
print(addr + " " + name)